# Generated by Django 4.2.20 on 2025-05-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pontuacao_maxima',
            field=models.IntegerField(default=0),
        ),
    ]
