# Generated by Django 5.2.4 on 2025-08-08 12:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='status_atual',
        ),
        migrations.AddField(
            model_name='perfil',
            name='ultima_atividade',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
