# Generated by Django 5.2.4 on 2025-08-21 23:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_perfil_status_atual_perfil_ultima_atividade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='bloqueado_por',
            field=models.ManyToManyField(blank=True, related_name='bloqueios', to=settings.AUTH_USER_MODEL),
        ),
    ]
